export enum ActionUser {
  USER_GET_LIST = 'USER_GET_LIST',
  USER_GET_LIST_SUCCES = 'USER_GET_LIST_SUCCES',
  USER_GET_LIST_FAILURE = 'USER_GET_LIST_FAILURE',
  USER_CONNECT = 'USER_CONNECT',
  USER_CONNECT_SUCCES = 'USER_CONNECT_SUCCES',
  USER_CONNECT_FAILURE = 'USER_CONNECT_FAILURE'
}
