export enum ActionRoom {
  ROOM_GET_LIST = 'ROOM_GET_LIST',
  ROOM_GET_LIST_SUCCESS = 'ROOM_GET_LIST_SUCCESS',
  ROOM_GET_LIST_FAILURE = 'ROOM_GET_LIST_FAILURE',
  ROOM_SELECT = 'ROOM_SELECT',
  ROOM_CREATE = 'ROOM_CREATE',
  ROOM_MESSAGE_GET_LIST = 'ROOM_MESSAGE_GET_LIST',
  ROOM_MESSAGE_GET_LIST_SUCCESS = 'ROOM_MESSAGE_GET_LIST_SUCCESS',
  ROOM_MESSAGE_GET_LIST_FAILURE = 'ROOM_MESSAGE_GET_LIST_FAILURE',
  ROOM_MESSAGE_SEND= 'ROOM_MESSAGE_SEND',
  ROOM_MESSAGE_SEND_SUCCESS = 'ROOM_MESSAGE_SEND_SUCCESS',
  ROOM_MESSAGE_SEND_FAILURE = 'ROOM_MESSAGE_SEND_FAILURE',
}
